### ISSUE TITLE
3.0 Beta release checklist

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#15326]
- [x] Functionally complete (according to a per version required prerequisite list).
- [x] No refactoring remaining.
- [x] All beta milestone items addressed.
- [x] Public API is frozen.  An application that works with a beta should work with all subsequent versions.
- [x] Triage open (non-triaged) issues since previous beta release. For each:
  - Add appropriate triage tag
  - Add appropriate branch tag (if obvious enough)
  - Add milestone (if relevant)
  - Close (if possible)
  - For beta-1: it is since the beginning of development of the current version (i.e. branch point).  For issues which are already triaged, only bugs without the current version and a set milestone need to be looked at.  
- [x] Triage all TODO(current release) items.  For each:
  - Remove
  - Create issue with triage and branch tag & milestone
- [x] Triage issues Coverity has tagged as high impact or above.  For each:
  - Assign severity on Coverity
  - Raise issue (if required)
  - Resolve on Coverity (if possible)
- [x] Coveralls coverage has not decreased overall from the previous release.
- [x] ~Have a pass through all new/changed APIs to ensure consistency, fixing those that aren’t.~
- [x] Confirm that all new public functions and macros are documented.
  - Check missingcrypto.txt for erroneous entries.
- [x] Check that new exported symbols (in the static build) are named correctly (ossl_ prefix).
- [x] Clean builds in GitHub Actions ~Travis and Appveyor~.
- [x] run-checker.sh succeeds.
- [x] Builds and passes tests on all primary, secondary and FIPS platforms.
- [x] A passing OTC ready for beta vote.

Outstanding items in specifics list:
- [x] EVP is the recommended API, it must be feature-complete compared with the functionality available using lower-level APIs.
  - Anything that isn’t available must be put to an OTC vote to exclude.
  - The apps are the minimum bar for this, subject to exceptions noted below.
- [x] Deprecation List Proposal: DH_, DSA_, ECDH_, ECDSA_, EC_KEY_, RSA_, RAND_METHOD_.
  - Does not include macros defining useful constants (e.g. SHA512_DIGEST_LENGTH).  
  - Excluded from Deprecation: `EC_`, `DSA_SIG_`, `ECDSA_SIG_`.
  - There might be some others.
  - Review for exceptions.
  - The apps are the minimum bar to measure feature completeness for the EVP interface: rewrite them so they do not use internal nor deprecated functions (except speed, engine, list, passwd -crypt and the code to handle the -engine CLI option).  That is, remove the suppression of deprecated define.  Proposal: drop passwd -crypt (OMC vote required)
  - Compile and link 1.1.1 command line app against the master headers and library.  Run 1.1.1 app test cases against the chimera.  Treat this as an external test using a special 1.1.1 branch.
  - Deprecated functions used by libssl should be moved to independent file(s), to limit the suppression of deprecated defines to the absolute minimum scope.
- [x] Draft documentation (contents but not pretty)
  - Need a list of things we know are not present - including things we have removed.
  - We need to have mapping tables for various d2i/i2d functions.
  - We need to have a mapping table from “old names” for things into the OSSL_PARAMS names.
  - Documentation addition to old APIs to refer to new ones (man7).
  - Documentation needs to reference name mapping.
  - All the legacy interfaces need to have their documentation pointing to the replacement interfaces.
- [x] ~Review (and maybe clean up) legacy bridge code.~
- [x] Review TODO(3.0) items #12224. Remaining ones in #15325
- [x] Source checksum script.
- [x] Review of functions previously named _with_libctx.
- [x] Encoder fixers (PKCS#8, PKCS#1, etc).
- [x] ~Encoder DER to PEM refactor.~
- [x] Builds and passes tests on all primary, secondary and FIPS platforms.
- [x] Complete make fipsinstall.
- [x] Query provider parameters (name, version, …) from the command line.
- [x] Setup buildbot infrastructure and associated instructions.
- [x] More specific decoding selection (e.g. params or keys).
- [x] ~Example code covering replacements for deprecated APIs.~
- [x] Drop C code output options from the apps (OMC approval required).
- [x] Address 3.0beta1 milestones.

**Comment by h-vetinari** [comment]
The issues under label ["tmp: fix in beta"](https://github.com/openssl/openssl/labels/tmp%3A%20fix%20in%20beta) should probably also be looked at (or the label removed).

**Comment by paulidale** [comment]
The _address 3.0beta1 milestones_ covers these, or at least it should.

**Comment by h-vetinari** [comment]
Another container where relevant issues were once collected (before the beta1 milestone existed), with some still open: https://github.com/openssl/openssl/projects/2

**Comment by h-vetinari** [comment]
BTW, it might make sense to use subpoints (e.g. not sure if everything under deprecation list - like the chimera as CI - is done already)?

GH supports this; the following
```
* [ ] outer
  * [ ] inner - mandatory
  * [x] inner - done
* [ ] outer
  * inner - either
  * inner - or
```
will produce
* [ ] outer
  * [ ] inner - mandatory
  * [x] inner - done
* [ ] outer
  * inner - either
  * inner - or

**Comment by paulidale** [comment]
I didn't know how to do this :)

**Comment by mattcaswell** [comment]
> Coveralls coverage has not decreased overall from the previous release.

1.1.1 release commit coveralls build is here:
https://coveralls.io/builds/18935212

Reported as 62.64%

Most recent build is here:
https://coveralls.io/builds/39765675

Reported as 63.55%

So barring a major problem between now and the beta release we should be fine with this one.

**Comment by t8m** [comment]
> Reported as 63.55%

It is totally unclear to me what the actual coverage is because if you look at the page the detailed message is `133562 of 205929 relevant lines covered (64.86%)`. Is the 63.55% number about percentage of covered files? Or what does the number mean?

**Comment by mattcaswell** [comment]
> Is the 63.55% number about percentage of covered files? Or what does the number mean?

Actually that's a really good question. I have no idea - I hadn't noticed this discrepancy. In the older 1.1.1 build these two numbers are the same. But in the most recent build they are different. Both are higher than the 1.1.1 figure so its good enough for our purposes...but I don't know how to interpret it.

**Comment by paulidale** [comment]
It builds the codes and I believe it counts the lines executed vs total lines from that.  Not a great metric given the number of configuration options we've got.

**Comment by mattcaswell** [comment]
The OTC passed the following vote:

````
topic: OTC approve the release of 3.0 beta1 on Thursday 17th June on the basis
       that: 1) all current approved PRs with the beta1 milestone are merged
       2) issues #15755 and #15756 are resolved 3) We accept that VMS does not
       currently pass tests but expect it to do so before 3.0 final (issue
       #15757)
````
All current PRs with the beta1 milestone have now been merged, and issues #15755 and 15756 are resolved. Therefore all OTC conditions are met. Closing this issue.
