### ISSUE TITLE
Support the SSLKEYLOGFILE environment variable

### ISSUE THREAD

**Issue by hlandau** [openssl/openssl#22660]
Currently we support the keylog format with an API, and the keylog format is [now under standardization](https://datatracker.ietf.org/doc/html/draft-thomson-tls-keylogfile-01)).

Some implementations allow this to be enabled at runtime using the `SSLKEYLOGFILE` environment variable. We could consider supporting this.
```[tasklist]
### Tasks
- [x] Implement addative callback for sslkeylog file
- [x] output key log data to a file if SSLKEYLOGFILE env is set
- [x] serialize output data in callback handler
- [x] document use of SSLKEYLOGFILE
- [x] implement test for recording and validating contents of SSLKEYLOGFILE
```

**Comment by nhorman** [comment]
@nhorman @mattcaswell  to refine this into a specific set of tasks and feature descriptions.

* Multithreaded behavior
* Build time vs. Run time selection
* All apps vs only openssl-apps.

**Comment by nhorman** [comment]
My thoughts:
* The ability to support SSLKEYLOGFILE should be a build time opt-in selection - i.e. users should be able to configure SSLKEYLOGFILE support for consumer at build time, or prevent them from using it
*  We (I think) want to get SSLKELOGFILE via safe_getenv, to prevent parent processes from unduly influencing child process logging capabilities (possible security risk otherwise)?
* we may want to create a public api to do this redirection (similar to set_keylog_file)
* Do we want to append a token to the log file name to separate logging of different contexts
* keylog_callback should perhaps implement a mutex to support multithreaded use

**Comment by hlandau** [comment]
> My thoughts:
> 
>     * The ability to support SSLKEYLOGFILE should be a build time opt-in selection - i.e. users should be able to configure SSLKEYLOGFILE support for consumer at build time, or prevent them from using it

:+1:
 
>     * We (I think) want to get SSLKELOGFILE via safe_getenv, to prevent parent processes from unduly influencing child process logging capabilities (possible security risk otherwise)?

:+1:

>     * we may want to create a public api to do this redirection (similar to set_keylog_file)

IMO, an application should be able to use SSLKEYLOGFILE and an existing keylog callback without them interfering with one another. There should also be an API for an application to override whatever behaviour is default regarding SSLKEYLOGFILE.

>     * Do we want to append a token to the log file name to separate logging of different contexts

No; this violates the "API" people expect from SSLKEYLOGFILE.
See https://datatracker.ietf.org/doc/html/draft-thomson-tls-keylogfile-01

>     * keylog_callback should perhaps implement a mutex to support multithreaded use

This is for the provider of the callback to do IMO.
