### ISSUE TITLE
Revise documentation for some EC_GROUP_* methods 

### ISSUE THREAD

**Issue by romen** [openssl/openssl#8630]
While working on #8555 ([comment](https://github.com/openssl/openssl/pull/8555/files#r270242827)) I noticed that the documentation of the `RETURN VALUES` for `EC_GROUP_get_order`, `EC_GROUP_get_cofactor`, `EC_GROUP_get_curve_name`, `EC_GROUP_get_asn1_flag`, `EC_GROUP_get_point_conversion_form` and `EC_GROUP_get_degree` is incorrect (and should be fixed also in `1.1.1`, at least).

In the same file, we are also missing an `HISTORY` section (other than for the function being added in #8555).

# Older Branches

1.0.2 and 1.1.0 documentation is also incorrect, but they are in security fix only mode, so probably this fix won't be merged in the older branches.

# Good first issue for new contributors

I believe this is a _good first issue_ as it would help new contributors familiarize with the `EC` submodule and with the project workflow, while being self contained: fixing it should only require changes to `doc/man3/EC_GROUP_copy.pod`.

# Recommended reading

It's a good idea to familiarize with #7854 about the preferred style for the `HISTORY` sections as a guideline to fill the new section.

## TODO

- [x] fix the documentation of the `RETURN VALUES` section in `doc/man3/EC_GROUP_copy.pod`
  - [x] `EC_GROUP_get_order`
  - [x] `EC_GROUP_get_cofactor`
  - [x] `EC_GROUP_get_curve_name`
  - [x] `EC_GROUP_get_asn1_flag`
  - [x] `EC_GROUP_get_point_conversion_form`
  - [x] `EC_GROUP_get_degree`
- [ ] check the other functions documented in this file for discrepancies
- [ ] populate the `HISTORY` section

_edit: add recommended reading_
_edit: updated todo_

**Comment by vilvarajintel** [comment]
submitted changes for review at https://github.com/openssl/openssl/pull/8847

**Comment by vilvarajintel** [comment]
updated PR is at https://github.com/openssl/openssl/pull/9195

**Comment by jayaram-intel** [comment]
Submitted changes for review at #9664 
Please review it.

**Comment by jayaram-intel** [comment]
Hi @romen 
Please review the changes available at #9664 

Thanks
Jayaram Matta

**Comment by romen** [comment]
Apologies @jayaram-intel I lost track of this!

I will probably manage to get to finally review the changes next week!

**Comment by jayaram-intel** [comment]
Sure @romen , you can review the changes on next week.

**Comment by jayaram-intel** [comment]
Hi @romen
Please review the changes available at #9664

Thanks
Jayaram Matta

**Comment by jayaram-intel** [comment]
Hi @romen
You can close this issue, Corresponding PR #9664 is already closed.

Thanks
Jayaram Matta

**Comment by romen** [comment]
I am keeping this open in case someone wants to volunteer to address also the HISTORY section.

I am quite sure some of these functions, especially the setters/getters, might have come during lettered releases of 1.1.0 or 1.1.1

It would still be nice to populate the history section listing when functions were added.

**Comment by jayaram-intel** [comment]
okay @romen .

**Comment by levitte** [comment]
@romen, do you still want to keep it open?  It's been almost a year!

**Comment by romen** [comment]
@levitte one can always keep dreaming that new contributors would appear from the community in search of good first issues to start from!

**Comment by slontis** [comment]
The following names all existed in 0.98 https://github.com/openssl/openssl/blob/OpenSSL_0_9_8-stable/util/libeay.num
(I didnt look further back than this).
So it is fairly pointless documenting this.

EC_GROUP_copy, EC_GROUP_set_generator
EC_GROUP_set_seed, EC_GROUP_get_seed_len, EC_GROUP_get0_seed
EC_GROUP_dup, EC_GROUP_method_of, 
EC_GROUP_get_cofactor, EC_GROUP_get0_generator
EC_GROUP_get_order,EC_GROUP_get_trinomial_basis,EC_GROUP_get_pentanomial_basis, EC_GROUP_get_basis_type
EC_GROUP_check_discriminant,
EC_GROUP_get_point_conversion_form,EC_GROUP_set_point_conversion_form
EC_GROUP_set_curve_name, EC_GROUP_get_curve_name,
EC_GROUP_check, EC_GROUP_cmp
EC_GROUP_get_asn1_flag, EC_GROUP_set_asn1_flag
EC_GROUP_get_degree

**Comment by romen** [comment]
We can probably close it then! Thanks @slontis for the check!

**Comment by slontis** [comment]
I think 'check the other functions documented in this file for discrepancies' is a non goal here..
There are a couple of functions left however that I have added..
