### ISSUE TITLE
Inconsistent manual section order; HISTORY

### ISSUE THREAD

**Issue by romen** [openssl/openssl#8631]
The placement of the `HISTORY` section across different manpages is not consistent at the moment: sometimes it's before `SEE ALSO` and sometimes between `SEE ALSO` and `COPYRIGHT`.

# Recommended reading

- This is related to issue #8304 (which reported a similar ordering issue) and to #8338 which fixed it for the `EXAMPLES` vs `RETURN VALUES`.
- It's a good idea to familiarize with #7854 about the preferred style for the `HISTORY` sections in case similar edits are required.

# Good first issue

I believe these documentation issues are a good candidate for new contributors as they are beneficial in familiarizing with the project.

# TODO

- [x] _(optional)_ expand #8338 `util/find-doc-nits` changes to detect out of order sections
- [ ] reorder `HISTORY` sections across all `.pod` files
- [ ] _(optional)_ edit where necessary to conform to #7854 style for `HISTORY` sections

**Comment by joshuagl** [comment]
I'd like to work on this as my first contribution to OpenSSL. I'm curious as to whether this would be considered a trivial change, or whether I need to get the CLA signed before I can submit a PR?

My WIP patches change it so that `HISTORY` comes after `SEE ALSO`, as this seems to be much more common in OpenSSL man pages.

**Comment by mattcaswell** [comment]
Probably a CLA will be needed. You can start work on it though without the CLA - it just needs to be there before the PR is merged.

**Comment by joshuagl** [comment]
Thanks @mattcaswell, I'll start figuring out the CLA in parallel with working on (and proposing) changes.

**Comment by joshuagl** [comment]
I'm working on getting the CLA signed and thought it would be useful to check in here and update with progress.

I've implemented the first two items on the checklist, I still need to review the HISTORY section of the files I've changed for consistency and conformance to the guidelines in #7854.

# TODO
* [x]  _(optional)_ expand #8338 `util/find-doc-nits` changes to detect out of order sections - in joshuagl@6ea193d9 and joshuagl@9f084e8e
* [x]  reorder `HISTORY` sections across all `.pod` files - in joshuagl@07129422
* [ ]  _(optional)_ edit where necessary to conform to #7854 style for `HISTORY` sections
